### ISSUE TITLE
[positive] Test on Steam Deck

### ISSUE THREAD

**Issue by leom403** [AdguardTeam/AdGuardVPNCLI#11]
Run curl and commands under Linux in my Steam Deck. **It works great!**

Adguard distrib: 
adguardvpn-cli-0.99.45-linux-x86_64

Linux OS params: 
Operating System: SteamOS
Kernel: Linux 6.1.52-valve16-1-neptune-61
Architecture: x86-64
Hardware Vendor: Valve
Hardware Model: Jupiter
Firmware Version: F7A0120
Firmware Date: Fri 2023-12-01

**Comment by sfionov** [comment]
Good to know! Thank you for feedback.
