### ISSUE TITLE
[CLI] Add a command to view license info

### ISSUE THREAD

**Issue by leom403** [AdguardTeam/AdGuardVPNCLI#12]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

is there a command to check the remaining traffic on your account?

**Comment by Rootdiv** [comment]
Need the ability to check traffic in a free account.
P.S. Life huck: use AdGuardVPN Extension

**Comment by leom403** [comment]
> Need the ability to check traffic for free account in adguradvpn-cli P.S. Life huck: use AdGuardVPN Extension for traffic monitoring.

right
Well.. i living from Russia and before i start using adguradvpn-cli i can't connect via Google Chrome Add-on. It says 'connection block 'coz you living in Russia'. 
After succes installition i can use web-addon :)

**Comment by Rootdiv** [comment]
> > Need the ability to check traffic for free account in adguradvpn-cli P.S. Life huck: use AdGuardVPN Extension for traffic monitoring.
> 
> right Well.. i living from Russia and before i start using adguradvpn-cli i can't connect via Google Chrome Add-on. It says 'connection block 'coz you living in Russia'. After succes installition i can use web-addon :)

Да, у меня при отсутствии подключения через adguradvpn-cli расширение пишет, что все серверы отключены.

Yes, I'm if there is no connection via adguradvpn-cli the extension write that all servers are offline.

**Comment by AlekseyMishanin** [comment]
@sfionov What do you think about this? It seems like a good idea. Maybe it's worth adding a new subcommand for profile information (license, traffic, and so on)?
