### ISSUE TITLE
Could socks mode accect proxy redirect from other proxy software?

### ISSUE THREAD

**Issue by lqdflying** [AdguardTeam/AdGuardVPNCLI#13]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I setup socks mode, but when I setup a proxy to 127.0.0.1:1080. it doesn't work.
```log
root@vultr:~# adguardvpn-cli config show
Current configuration:
	Mode: socks
	Socks port: 1080
	DNS upstream: Default (provided by AdGuard VPN)
	No routes: on
	Set system DNS: off
	Send crash: on
	Update channel: BETA
	Show hints: Default (on)
	Debug logging: on
root@vultr:~# 
```

**Comment by Rootdiv** [comment]
> I setup socks mode, but when I setup a proxy to 127.0.0.1:1080. it doesn't work.

Confirm. Other port too doesn't work.
maindiv@UbuntuMate:~$ adguardvpn-cli config show
Current configuration:
	Mode: socks
	Socks port: 88
	DNS upstream: Default (provided by AdGuard VPN)
	No routes: off
	Set system DNS: on
	Send crash: on
	Update channel: BETA
	Show hints: Default (on)
	Debug logging: Default (off)
maindiv@UbuntuMate:~$

**Comment by lqdflying** [comment]
it works, my mistake. I would close this case.
