### ISSUE TITLE
Command-line completion (tab completion / autocompletion)

### ISSUE THREAD

**Issue by AlekseyMishanin** [AdguardTeam/AdGuardVPNCLI#18]
### Issue Details

When I type the `adguardvpn-cli` subcommand on the command line, I have to type it in full. It's not very user friendly. For example, this is how I suffer:

[adguardvpn_cli_issue.webm](https://github.com/AdguardTeam/AdGuardVPNCLI/assets/39388854/1d600af6-b5ed-4875-bd10-af28c5ef0ad1)

Please allow me to use your command-line VPN client the same way I use `grep`:

[grep_example.webm](https://github.com/AdguardTeam/AdGuardVPNCLI/assets/39388854/b2a7f46c-6ca1-4e8d-a8b4-6a3c6ff1225e)

### Proposed solution

Improve the `install.sh`

### Alternative solution

Ignore me

**Comment by sfionov** [comment]
@AlekseyMishanin Fixed in nightly 1.1.92
