### ISSUE TITLE
Apps and sites exclude

### ISSUE THREAD

**Issue by Jipeg** [AdguardTeam/AdGuardVPNCLI#21]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I wish i have an option to have excluded apps and/or websites like in GUI version. Are you planning to implement this in recent future?

**Comment by sfionov** [comment]
Hello! 

Thank you for feature request.

Created two new issues for your feature request, you may track them.
