### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by korotobo** [AdguardTeam/AdGuardVPNCLI#25]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Operating System: openSUSE Tumbleweed 20240523
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.9.1-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Memory: 13.6 ГиБ of RAM
Graphics Processor: AMD Radeon Vega 8 Graphics
Manufacturer: Acer
Product Name: Aspire A315-42G
System Version: V1.11

I understand that these are most likely system features, but when connecting with --no-fork, I get this result:

25.05.2024 22:27:19.608902 INFO  [6337] STANDALONE_CLIENT set_outbound_interface: Outbound interface is not specified, trying to detect it automatically
25.05.2024 22:27:19.608997 INFO  [6337] STANDALONE_CLIENT set_outbound_interface: $ ip -o route show to default
25.05.2024 22:27:19.616402 INFO  [6337] STANDALONE_CLIENT set_outbound_interface: Using automatically detected outbound interface: wlp4s0
25.05.2024 22:27:19.616637 INFO  [6337] VPNCORE vpn_open: [0] ...
25.05.2024 22:27:19.616745 INFO  [6337] DNS proxy init: Initializing proxy module...
25.05.2024 22:27:19.616838 INFO  [6337] DNS forwarder init: Initializing forwarder...
25.05.2024 22:27:19.616878 INFO  [6337] DNS forwarder init: Initializing upstreams...
25.05.2024 22:27:19.616907 INFO  [6337] DNS forwarder init: Initializing upstream 192.168.3.1...
25.05.2024 22:27:19.616952 INFO  [6337] DNS forwarder init: Upstream created successfully
25.05.2024 22:27:19.616977 INFO  [6337] DNS forwarder init: Upstreams initialized
25.05.2024 22:27:19.617000 INFO  [6337] DNS forwarder init: Initializing the filtering module...
25.05.2024 22:27:19.617027 INFO  [6337] DNS forwarder init: Filtering module initialized
25.05.2024 22:27:19.617052 INFO  [6337] DNS forwarder init: Initializing the fallback filter...
25.05.2024 22:27:19.618446 INFO  [6337] Filter load: [0::::in_memory] load(): Unique domains table size: 36
25.05.2024 22:27:19.618485 INFO  [6337] Filter load: [0::::in_memory] load(): Non-unique domains table size: 0
25.05.2024 22:27:19.618510 INFO  [6337] Filter load: [0::::in_memory] load(): Shortcuts table size: 3
25.05.2024 22:27:19.618535 INFO  [6337] Filter load: [0::::in_memory] load(): CIDR table size: 0
25.05.2024 22:27:19.618560 INFO  [6337] Filter load: [0::::in_memory] load(): Leftovers table size: 1
25.05.2024 22:27:19.618585 INFO  [6337] Filter load: [0::::in_memory] load(): Badfilter table size: 0
25.05.2024 22:27:19.618609 INFO  [6337] Filter load: [0::::in_memory] load(): Approximate memory usage: 2K
25.05.2024 22:27:19.618634 INFO  [6337] dnsfilter init: Filter 0 added successfully
25.05.2024 22:27:19.618664 INFO  [6337] DNS forwarder init: Forwarder initialized
25.05.2024 22:27:19.618688 INFO  [6337] DNS proxy init: Initializing listeners...
25.05.2024 22:27:19.618776 INFO  [6337] listener before_run: [TP_UDP 127.0.0.1:35347] Listening on 127.0.0.1:35347 (UDP)
25.05.2024 22:27:19.618868 INFO  [6337] listener before_run: [TP_TCP 127.0.0.1:43997] Listening on 127.0.0.1:43997 (TCP)
25.05.2024 22:27:19.618988 INFO  [6337] DNS proxy init: Proxy module initialized
25.05.2024 22:27:19.619046 INFO  [6337] VPNCORE vpn_open: [0] Done
25.05.2024 22:27:19.619083 INFO  [6337] VPNCORE vpn_connect: [0] ...
25.05.2024 22:27:19.619111 INFO  [6337] VPNCORE run_event_loop: [0] Starting event loop...
25.05.2024 22:27:19.619296 INFO  [6337] VPNCORE run_event_loop: [0] Event loop has been started
25.05.2024 22:27:19.619351 INFO  [6337] VPNCORE vpn_connect: [0] Done
25.05.2024 22:27:19.619432 ERROR [6337] OS_TUNNEL_LINUX tun_open: ioctl TUNSETIFF failed: Operation not permitted
25.05.2024 22:27:19.619410 INFO  [6344] VPNCORE raise_state: [0] VPN_SS_CONNECTING
25.05.2024 22:27:19.619479 ERROR [6337] STANDALONE_CLIENT make_tun_listener: Failed to initialize tunnel: Failed to init tunnel
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
Unhandled Error

**Comment by sfionov** [comment]
@korotobo Currently `connect --no-fork` should be ran under `sudo -E` if you use adguardvpn-cli not under root user

**Comment by korotobo** [comment]
Thank you. It's working.
