### ISSUE TITLE
Install script lacks support for armv7 architectures

### ISSUE THREAD

**Issue by bleadev** [AdguardTeam/AdGuardVPNCLI#30]
### Please answer the following question for yourself before submitting an issue

- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN CLI version

1.0

### Environment

- OS: DietPi v9.4.2 (Based on Debian GNU/Linux 11 (bullseye))
- Device: Raspberry Pi 2 v1.1
- Architecture: armv7l

### Issue Details

Steps to reproduce:
1. Execute the install script on a device using armv7 architecture

### Expected Behavior

Script correctly setting the architecture to armv7 and proceeding with the install

### Actual Behavior

Script exits after printing `unsupported cpu type: armv7l`

### Additional Information

The issue seems to lie in the `set_cpu()` function which only sets architectures for amd64, aarch64, and mips. Successful installation can be achieved by setting the `cpu` variable at the script entrypoint to `armv7`.

**Comment by sfionov** [comment]
Fixed in [today's nightly](https://github.com/AdguardTeam/AdGuardVPNCLI/releases/tag/v1.0.3-nightly)
