### ISSUE TITLE
After deploying on the cloud server, it is inaccessible when it is turned on, but accessible when it is turned off.

### ISSUE THREAD

**Issue by chiheye** [AdguardTeam/AdGuardVPNCLI#31]
### Please answer the following question for yourself before submitting an issue

- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN CLI version

1.0

### Environment

- OS: centos stream 9
- Architecture: x86-64

### Issue Details

Steps to reproduce:
1.The service can be started and stopped normally.
2.Deployed on a cloud server.

### Actual Behavior

The Docker container requires access to the internet, hence it is deployed on a cloud server.

**Comment by sfionov** [comment]
@chiheye Hello! Can you please specify your setup? Where adguardvpn-cli is running - on host or inside Docker?

**Comment by aliafshany** [comment]
@chiheye it's because you are using it in TUN mode. Use SOCKS5 in order to access your server.

**Comment by chiheye** [comment]
> @chiheye Hello! Can you please specify your setup? Where adguardvpn-cli is running - on host or inside Docker?

inside Docker

**Comment by chiheye** [comment]
> @chiheye it's because you are using it in TUN mode. Use SOCKS5 in order to access your server.

I tried switching modes to TUN and SOCKS5, but neither could access the Docker container's port properly. If I disconnect from AdGuardVPNCLI, access is normal. The same situation occurs when I test it on my local laptop.
