### ISSUE TITLE
DNS Leaks when connected to VPN

### ISSUE THREAD

**Issue by Laitinlok** [AdguardTeam/AdGuardVPNCLI#34]
### Please answer the following question for yourself before submitting an issue

- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN CLI version

1.0

### Environment

- OS: OpenSUSE Tumbleweed
- Architecture: x86_64

### Issue Details

Steps to reproduce:
1. Set upstream dns as DoH server
2. Connect to VPN
3. Go to ipleak.net and both ISP DNS and VPN DNS is shown

### Expected Behavior

Only the VPN DNS is shown in ipleak.net

### Actual Behavior

Both ISP DNS and VPN DNS is shown

### Screenshots

<details><summary>Screenshot 1</summary>
![螢幕快照 2024-06-16 20-12-37](https://github.com/AdguardTeam/AdGuardVPNCLI/assets/63400461/0330c6c6-bb34-4f02-926d-dce104087f06)

</details>

**Comment by SelYui** [comment]
Could you please run the following command in your terminal and share the output with us?
`adguardvpn-cli config show`
This command will display your current AdGuard VPN configuration. With this information, we can better understand the issue and help you troubleshoot it.

**Comment by RonKhondji** [comment]
![Screenshot from 2024-08-28 18-11-50](https://github.com/user-attachments/assets/e88cc28f-45d1-42c0-b331-a9a6273d0de2)
