### ISSUE TITLE
How do i uninstall

### ISSUE THREAD

**Issue by githubUser01946** [AdguardTeam/AdGuardVPNCLI#37]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I would like to know what I should type in Konsole to uninstall this please.

**Comment by sfionov** [comment]
@githubUser01946 The same as install command but with additional `-u` parameter on the end.

Like `curl -fsSL https://raw.githubusercontent.com/AdguardTeam/AdGuardVPNCLI/master/scripts/release/install.sh | sh -s -- -v -u
`

Or you may just delete the following directories and files:
```
/opt/adguardvpn_cli
~/.local/share/adguardvpn-cli
/usr/local/bin/adguardvpn-cli
```
