### ISSUE TITLE
AdGuardVPN CLI don't work on the Keenetic

### ISSUE THREAD

**Issue by Ulrikheduard** [AdguardTeam/AdGuardVPNCLI#42]

**Comment by Ulrikheduard** [comment]
Hi! I can't install AdGuard vpn on the Keenetic router.

I enter all the VPN connection data for the router correctly but when I try to turn on the VPN I can’t connect to the Internet.![image](https://github.com/user-attachments/assets/ded8bf64-60e7-440f-8efb-c4db3754ba3c)

**Comment by Alex-302** [comment]
@Ulrikheduard Which country? IPsec may be blocked by ISP.

**Comment by Eugene-Savenko** [comment]
Если вы видите ошибку "Нет IP-адреса", с очень высокой вероятностью ваш провайдер блокирует IPsec, что очень актуально для РФ.

**Comment by Ulrikheduard** [comment]
В статусе отображается "готова", но подсвечивается желтым цветом и ip адрес не меняется. В приоритете подключений в настройках Keenetic vpn стоит на первом месте.

The status shows "ready", but is highlighted in yellow and the IP address does not change. In the connection priority in the settings, Keenetic vpn is in first place.

![image](https://github.com/user-attachments/assets/3834c40b-7d2c-4dfd-b4da-a5ec26815909)

**Comment by stralol** [comment]
Hi! Такая же ошибка, модель Keenetic speedster KN-3012. Какие тогда методы есть для работы AdguardVPN и Keenetic?

**Comment by Eugene-Savenko** [comment]
Если оператор блокирует IPsec, мы на это никак не повиляем. Ожидайте инструкции по настройке VPN CLI (VPN для Linux) для ваших устройств Keenetic.

**Comment by stralol** [comment]
Через другие протоколы, кроме Ipsec, ADguard не работает? Это был единственный способ установки на роутер?

**Comment by Eugene-Savenko** [comment]
Другие протоколы пока еще не поддерживаются.
Если оператор блокирует IPsec, методов нет никаких; рекомендуем ожидать поддержку VPN CLI.

**Comment by stralol** [comment]
Ожидание примерно сколько займет?

**Comment by Eugene-Savenko** [comment]
В ближайшее время будет готово, точными сроками не располагаем.

**Comment by stralol** [comment]
Решение готово? Полтора месяца прошло

**Comment by Eugene-Savenko** [comment]
https://adguardvpn-help.info/kb/ru/adguard-vpn-for-linux/setting-up-on-a-router/
