### ISSUE TITLE
DNS Leak detected with custom DNS set

### ISSUE THREAD

**Issue by AtlasUnbound** [AdguardTeam/AdGuardVPNCLI#46]
### Please answer the following question for yourself before submitting an issue

- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN CLI version

1.0

### Environment

- OS: ZorinOS

### Issue Details

Steps to reproduce:
1. set a custom dns
2.connect to ipleak
3.see isp dns instead

### Expected Behavior

custom DNS is used

### Actual Behavior

isp DNS is used

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Not sure what caused this, could be because I have quic on? But still happened without, as well as set system DNS, the issue continues.

**Comment by grumaxxx** [comment]
Closed as same to https://github.com/AdguardTeam/AdGuardVPNCLI/issues/34

**Comment by grumaxxx** [comment]
This will be fixed in the next release.
