### ISSUE TITLE
Not work remove exclusions site

### ISSUE THREAD

**Issue by Rootdiv** [AdguardTeam/AdGuardVPNCLI#52]
### Please answer the following question for yourself before submitting an issue

- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN CLI version

1.1.99

### Environment

- OS: Ubuntu v22.04
- Architecture: x86-64

### Issue Details

Steps to reproduce:
1. add site exclusions
2. try remove site exclusions

### Expected Behavior

removed site exclusions

### Actual Behavior

Not remove site exclusions

**Comment by Aydinv13** [comment]
@Rootdiv hi there!

Could you specify, is the exclusion not removed from the list or not applied once removed? Does it happen only with one domain? Is there an example of a domain?

Can you also please grab the debug logs:
perform this command `adguardvpn-cli config set-debug-logging on`, reproduce the problem and collect the logs using `adguardvpn-cli export-logs` then send them to qa@adguard.com.

**Comment by Rootdiv** [comment]
> Could you specify, is the exclusion not removed from the list or not applied once removed? Does it happen only with one domain? Is there an example of a domain?

Applying after deletion. If you request a list of domains in the exceptions, then all domains are displayed, including those that I wanted to delete. Deletion does not work with any domain.

**Comment by Aydinv13** [comment]
Could you show the output of `adguardvpn-cli config show` and send the logs to qa@adguard.com, please.

**Comment by Rootdiv** [comment]
After updating to version 1.1.101 the error does not reproduce, everything works as it should.

**Comment by Rootdiv** [comment]
> Could you show the output of `adguardvpn-cli config show` and send the logs to [qa@adguard.com](mailto:qa@adguard.com), please.

Sended the data to your email

**Comment by Rootdiv** [comment]
After updating to version 1.1.108 the error does not reproduce. Everything works as it should.
