### ISSUE TITLE
The exclusion list does not work correctly

### ISSUE THREAD

**Issue by Eksol** [AdguardTeam/AdGuardVPNCLI#61]
### Please answer the following question for yourself before submitting an issue

- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN CLI version

1.1.112

### Environment

- OS: OpenWRT

### Issue Details

Try opening Twitter and adding domains to the exception lists to add to the tunnel. 
![Скриншот 05 10 24_12 31 17](https://github.com/user-attachments/assets/d1e7f4b4-9c8b-4cdf-b1dc-2ce43ffd37a1)

### Expected Behavior

Traffic from the specified exception lists is expected to go through the tunnel.

### Actual Behavior

In reality this does not happen, there is no access to Twitter.
![Скриншот 05 10 24_14 00 28](https://github.com/user-attachments/assets/8abdea93-4736-452a-a5c6-62f030071c4b)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

After a recent server update, the problem with speed and ping has gone away with the adguardvpnwindows and adguardvpncli.

But in the adguardvpnsly version there are problems with the speed of loading videos from YouTube. Speedtest shows 200 mb. But in YouTube the speed is 10 mb.

**Comment by sfionov** [comment]
@Eksol I recommend also adding `"*.twimg.com"` and `t.co` to exclusions.

**Comment by Eksol** [comment]
> @Eksol I recommend also adding `"*.twimg.com"` and `t.co` to exclusions.

Thank you, this solved my problem.

**Comment by Eksol** [comment]
But the problem with speed in YouTube remains. In the speedtest the speed is under 300 MB, but in YouTube the video download speed is 10 MB. Is it just me or is Adguard cheating somewhere?

**Comment by est1977** [comment]
Добрый день! 
В роутере Keenetic Giga N-1012 попытался добавить в SELECTIVE "www.youtube.com"
_/ # adguardvpn-cli site-exclusions add "wwww.youtube.com"_
выдает результат:
_Successfully added 1 exclusions
Applying new settings...
Settings applied successfully
Connected to BERLIN in TUN mode, running on tun0_
Но ничего не открывает. 
Попытка написать без кавычек или полный адрес https://www.youtube.com/ 
_/ # adguardvpn-cli site-exclusions add https://www.youtube.com/_
выдает ошибку: 
_Skipped invalid exclusion: https://www.youtube.com/
Some of the specified exclusions are invalid. Please see the command help for supported formats
Nothing to change_
P.S. В режиме GENERAL все работает.
Подскажите, что делаю не так?

**Comment by Eksol** [comment]
> Добрый день! В роутере Keenetic Giga N-1012 попытался добавить в SELECTIVE "www.youtube.com" _/ # adguardvpn-cli site-exclusions add "wwww.youtube.com"_ выдает результат: _Successfully added 1 exclusions Applying new settings... Settings applied successfully Connected to BERLIN in TUN mode, running on tun0_ Но ничего не открывает. Попытка написать без кавычек или полный адрес https://www.youtube.com/ _/ # adguardvpn-cli site-exclusions add https://www.youtube.com/_ выдает ошибку: _Skipped invalid exclusion: https://www.youtube.com/ Some of the specified exclusions are invalid. Please see the command help for supported formats Nothing to change_ P.S. В режиме GENERAL все работает. Подскажите, что делаю не так?
> 
> p.s p.s. Добавил instagram.com и facebook.com, но доступ к ним также отсутствует

Нужно просто написать youtube.com
 Если хочешь поддомены добавить, то пропиши вот так *.googlevideo.com

**Comment by est1977** [comment]
> > Добрый день! В роутере Keenetic Giga N-1012 попытался добавить в SELECTIVE "www.youtube.com" _/ # adguardvpn-cli site-exclusions add "wwww.youtube.com"_ выдает результат: _Successfully added 1 exclusions Applying new settings... Settings applied successfully Connected to BERLIN in TUN mode, running on tun0_ Но ничего не открывает. Попытка написать без кавычек или полный адрес https://www.youtube.com/ _/ # adguardvpn-cli site-exclusions add https://www.youtube.com/_ выдает ошибку: _Skipped invalid exclusion: https://www.youtube.com/ Some of the specified exclusions are invalid. Please see the command help for supported formats Nothing to change_ P.S. В режиме GENERAL все работает. Подскажите, что делаю не так?
> > p.s p.s. Добавил instagram.com и facebook.com, но доступ к ним также отсутствует
> 
> Нужно исключение настроить в режим, когда в туннель отправляется только то что есть в списках исключений, и добавить ещё несколько других доменов с которых работает Ютуб. Посмотри мой список исключений, там кроме Ютуба ещё много других доменов.

Так у меня и стоит режим SELECTIVE (избранное через туннель), а не GENERAL и именно в SELECTIVE добавляю ютубы и инстаграмы

**Comment by est1977** [comment]
> > Добрый день! В роутере Keenetic Giga N-1012 попытался добавить в SELECTIVE "www.youtube.com" _/ # adguardvpn-cli site-exclusions add "wwww.youtube.com"_ выдает результат: _Successfully added 1 exclusions Applying new settings... Settings applied successfully Connected to BERLIN in TUN mode, running on tun0_ Но ничего не открывает. Попытка написать без кавычек или полный адрес https://www.youtube.com/ _/ # adguardvpn-cli site-exclusions add https://www.youtube.com/_ выдает ошибку: _Skipped invalid exclusion: https://www.youtube.com/ Some of the specified exclusions are invalid. Please see the command help for supported formats Nothing to change_ P.S. В режиме GENERAL все работает. Подскажите, что делаю не так?
> > p.s p.s. Добавил instagram.com и facebook.com, но доступ к ним также отсутствует
> 
> Нужно просто написать youtube.com Если хочешь поддомены добавить, то пропиши вот так *.googlevideo.com

писал так , но без кавычек пишет ошибку Skipped invalid exclusion:........

**Comment by Eksol** [comment]
> > > Добрый день! В роутере Keenetic Giga N-1012 попытался добавить в SELECTIVE "www.youtube.com" _/ # adguardvpn-cli site-exclusions add "wwww.youtube.com"_ выдает результат: _Successfully added 1 exclusions Applying new settings... Settings applied successfully Connected to BERLIN in TUN mode, running on tun0_ Но ничего не открывает. Попытка написать без кавычек или полный адрес https://www.youtube.com/ _/ # adguardvpn-cli site-exclusions add https://www.youtube.com/_ выдает ошибку: _Skipped invalid exclusion: https://www.youtube.com/ Some of the specified exclusions are invalid. Please see the command help for supported formats Nothing to change_ P.S. В режиме GENERAL все работает. Подскажите, что делаю не так?
> > > p.s p.s. Добавил instagram.com и facebook.com, но доступ к ним также отсутствует
> > 
> > 
> > Нужно просто написать youtube.com Если хочешь поддомены добавить, то пропиши вот так *.googlevideo.com
> 
> писал так , но без кавычек пишет ошибку Skipped invalid exclusion:........

Тогда подключай чатгпт, что бы он тебя носом тыкнул в ошибку. 
Работа сервиса идёт через множество разных доменов. Добавляя только один инстаграмм в списки исключений, проблема с доступом не решится.
