### ISSUE TITLE
Add Protect from DPI option

### ISSUE THREAD

**Issue by nshenderov** [AdguardTeam/AdGuardVPNCLI#66]
### Issue Details

Missing `Protect from DPI` option.

### Proposed solution

I would like to have DPI protection on the Linux client, which currently lacks this feature compared to other platforms.

**Comment by nshenderov** [comment]
Got confused, this option is part of a different AdGuard app.

**Comment by sfionov** [comment]
Yes, AdGuard CLI will have this functionality when it's released
