### ISSUE TITLE
Add terminal autocompletion

### ISSUE THREAD

**Issue by snappyapple632** [AdguardTeam/AdGuardVPNCLI#70]
### Issue Details

Autocompletion in the terminal is a simple quality of life feature implemented in many Linux programs that helps users avoid typos and save a bit of time. Currently, adguardvpn-cli does not have autocompletion.

### Proposed solution

Add autocompletion for adguardvpn-cli commands (i.e. connect, disconnect, update).

### Alternative solution

Implement a Unix-like options system for adguardvpn-cli (i.e. -c for "connect", -d for "disconnect", -u for "update").

**Comment by sfionov** [comment]
@snappyapple632 This is already done in #18 and included in 1.1 release

You may find the instruction in the install script output
<img width="689" alt="image" src="https://github.com/user-attachments/assets/a6d9705c-22d7-498c-922f-3e68d4128149">
