### ISSUE TITLE
Feature Request: Prompt for Login Details When Required

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/AdGuardVPNCLI#72]
### Issue Details

Currently, when the AdGuard VPN CLI requires authentication but the user is not logged in, an error message is displayed, prompting the user to enter a separate adguardvpn login command. This disrupts workflow by requiring an extra step and could be streamlined to improve user experience.

### Proposed solution

When a command that requires authentication is run and the user is not logged in, the CLI should automatically prompt for login credentials rather than displaying an error. This would allow the user to log in directly within the context of the initial command. Upon successful authentication, the original command should execute as intended, minimizing disruptions and aligning with expected behavior in CLI tools.

**Comment by sfionov** [comment]
This only makes workflow inconsistent since it is expected for CLI command to do only one thing.
