### ISSUE TITLE
Login Unknown error. Failed to track install

### ISSUE THREAD

**Issue by chiheye** [AdguardTeam/AdGuardVPNCLI#73]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Login Unknown error. Failed to track install.
logs:
1.11.2024 11:29:32.332771 ERROR [144] AuthenticatorImpl fetch_vpn_token: vpn_token_request failed: Timed out
11.11.2024 11:32:32.331829 ERROR [155] AuthenticatorImpl fetch_vpn_token: vpn_token_request failed: Timed out
11.11.2024 11:46:48.914791 ERROR [142] CLI_APP check_update: check_app_updates_request failed: Timed out
11.11.2024 11:47:31.796784 ERROR [145] CLI_APP check_update: check_app_updates_request failed: Timed out
11.11.2024 11:48:42.806475 ERROR [148] CLI_APP check_update: check_app_updates_request failed: Timed out
11.11.2024 11:51:45.308582 ERROR [282] CLI_APP check_update: check_app_updates_request failed: Timed out
11.11.2024 11:57:45.891555 ERROR [321] CLI_APP check_update: check_app_updates_request failed: Timed out
config:
[1mUser-Agent[0m: AdGuardVPNCLI/1.1.126 (Linux 4.4.302+; U; x86_64) VpnLibs/0.14.31
[1mApplication ID[0m: d2211aa9bfb6dbeafe9bafd60f50675e
[1mCurrent configuration:
[0m	Data directory: /root/.local/share/adguardvpn-cli
	Mode: socks
	SOCKS port: 1080
	SOCKS host: 172.17.0.11
	SOCKS username: chiheye
	DNS upstream: Default (provided by AdGuard VPN)
	Tunnel routing mode: not set
	Set system DNS: not set
	Send crash: not set
	Update channel: RELEASE
	Use QUIC: Default (off)
	Show hints: Default (on)
	Debug logging: Default (off)
	Show notifications: Default (off)

**Comment by sfionov** [comment]
@chiheye To deal with your issue we need debug logs.

Here's how to get them:
1. Enable debug logging `adguardvpn-cli config set-debug-logging on`
2. Reproduce the issue
3. Export logs using `adguardvpn-cli export-logs`
4. Send them to devteam@adguard.com, in message title please specify github task and time when issue is reproduced.
5. Restore debug logging setting: `adguardvpn-cli config set-debug-logging off`

**Comment by chiheye** [comment]
The email has been sent. Thank you for your support.

**Comment by sfionov** [comment]
@chiheye Looks like there's a problem with availability of a backend mirror. Is link https://guidedemonstration.live/cdn-cgi/trace opens for you ?

**Comment by zzebrum** [comment]
@chiheye a gentle reminder :)

**Comment by zzebrum** [comment]
Please, re-open if needed.
