### ISSUE TITLE
opensuse: cant start without root

### ISSUE THREAD

**Issue by ReLoneR1** [AdguardTeam/AdGuardVPNCLI#74]
### Please answer the following question for yourself before submitting an issue

- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN CLI version

1.1.126

### Environment

- OS:
opensuse tumbleweed x86-64

### Issue Details

Steps to reproduce:
1. install on opensuse
2. adguardvpn-cli login
3. adguardvpn-cli connect

### Expected Behavior

sudo asks for password -> connect 

### Actual Behavior

sudo asks for password -> failed to connect
running under root -> connect

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ReLoneR1** [comment]
sent a letter with logs to the devteam@adguard.com

**Comment by sfionov** [comment]
@ReLoneR1 Can you please try the nightly version? There's a problem with `-E` sudo flag on OpenSUSE and Fedora, and workaround for that was added to 1.2 nightlies.

**Comment by ReLoneR1** [comment]
nightly does the trick, it works as expected, thank you
